name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: |
          npm run build

      - name: Verify build files
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Generating directory tree for nextbuild"
          find nextbuild -type f > nextbuild-directory-tree.txt
          echo "Directory tree generated:"
          cat nextbuild-directory-tree.txt

      - name: Move build files
        run: |
          mkdir -p gh-pages
          cp -r nextbuild/* gh-pages/
          cp nextbuild-directory-tree.txt gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONALACCESSTOKEN }}
          publish_dir: ./gh-pages
